run_baseline:
  region: FVG
  dates:
    start: 2025-01-01
    end: 2026-01-01
  save_images: false
  workers: 4
  force: 4
  fold_rm:
    strategy: one_vs_rest
    ratio: 0.7
    test_ratio: 0.3
    seed: 42
    gpu: false

