#run_baseline:
#  region: FVG
#  dates:
#    - 2009-01-02
#  clean: 0
#  force: 0
#  clustering: false
#  debug: false
#  just_cut: false
#  save_images: false

run_baseline:
  region: FVG
  dates:
    - 2009-01-02
  clean: 1
  force: 3
  clustering: false
  debug: false
  just_cut: true
  save_images: false
