services:
  weather:
    image: eliussolis/sergio:latest
    env_file: .env                       # for data downloads (can be omitted if data is already downloaded in tmp_data)

    volumes:
      - ./runs:/app/runs                 # output folder
      - ./config.yaml:/app/config.yaml   # config file location
      - ./xmls:/app/xmls                 # XML forecast files location
      - ./tmp_data:/app/tmp_data         # optional
